### ISSUE TITLE
 The invalid login from the user shows misleading message

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#145] opened 2016-06-30 06:27 UTC
#=== Problem Description ===================================
#===========================================================
The invalid login from the user shows the message "User '123.12.12.12' logged in" which can be improvised to something like 	"User '123.12.12.12' failed log in"

**Comment by alinefm** [comment] 2016-07-05 14:43
The UI needs to be updated as now the backend is logging failed actions.

**Comment by danielhb** [comment] 2016-07-28 14:15
I can't reproduce this problem. The message shown on a failed login attempt, as shown in wokd log:

```
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [28/Jul/2016:11:11:45] "POST /login HTTP/1.0" 401 1674 "https://localhost:8001/login.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"

```

And the user message in the UI is:


![image](https://cloud.githubusercontent.com/assets/866780/17215811/89b90fd0-54b4-11e6-904c-9f09e6b31ee7.png)



Am I missing something here?

**Comment by peterpennings** [comment] 2016-08-01 17:40
Hi danielhb, 

You can see the error log message on the settings panel in Wok (user log). When we have a failed login, the message on Wok -> Seetings is "User '<user>' login". The message should be "User '<user>' failed log in". But on backend API, the message is still wrong. Does anyone have any updates about this issue?

**Comment by peterpennings** [comment] 2016-08-10 12:25
@alinefm @danielhb any updates on this issue?

**Comment by danielhb** [comment] 2016-08-10 15:52
@peterpennings this seems like a backend bug reporting the wrong message on a failed user login attempt. I'll remove the UI tag from this bug.

**Comment by lcorreia** [comment] 2016-08-11 15:22
In backend, that message is already using present verb, giving an idea of not completed action yet. Another improvement done is to show the failure reason after the log message (original exception).

For translation reasons, we are not prepending "Failed to" to the messages (does not work to all languages). Creating a failed version for each user log message is not worth in my opinion (too much work).

The UI is capable of show a label [Failed] or the entry in different color based on status code of the request (>=400 is failed). That was the original idea and I think that's why Aline marked it as a UI.

**Comment by samhenri** [comment] 2016-08-11 16:34
@laggarcia @danielhb @alinefm Can we close this issue and open a new one for this change in Settings page or label this issue again as UI and we apply the change on Wok User Log table?

I think the same label for plugin/application wouldn't look nice because in the whole error message because the text can be long and we trim if it doesn't fit the column width so it would be too much information going on the same column.
I've tried this with Chrome Dev Tools, it looks similar to System Services status:
![response_errors](https://cloud.githubusercontent.com/assets/326107/17596521/2d20b43e-5fc8-11e6-84f5-79c307f9f525.png)

Personally I think we should add a new column next to the messages with the response code and then use the labels on the response code with a tooltip.

**Comment by lcorreia** [comment] 2016-08-12 14:25
Samuel, I like the labels for status code in your screenshot.
I just suggest that we leverage this opportunity to reduce the excessive spacing between columns, in order to see more of the message.
I'm ok to relabel this as UI.

**Closed** 2016-08-22 16:57 UTC
Labels: bug
