### ISSUE TITLE
User activity  - The user activity log not captured if the wok-req.log goes missing from the logging path

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#126] opened 2016-06-03 07:07 UTC
#=== Problem Description ===================================
#===========================================================
The user activity log does not get captured for all the user activities performed if the wok-req.log
goes missing from the /var/log/wok path or the specified path in wok.conf. The log gets generated again
only when the wokd service is restarted.

#=== Steps to Reproduce ====================================
#===========================================================
1. Login to the machine from the UI screen.
2. Remove the wok-req.log from the /var/log/wok path.
3. Perform some user activity from the UI page.
4. Check for activity log on the UI

**Comment by alinefm** [comment] 2016-07-05 13:53
Maybe we should place wok-req.log in a safer directory than the log directory to avoid user removes it.
As it is an input file for a wok feature it would be better to move to /data dir.

And also regenerate the file if needed on runtime.

**Comment by lcorreia** [comment] 2016-09-23 14:33
I cannot reproduce this issue on RHEL 7.2. Let me know details if you can still reproduce it.
There were some changes that probably fixed it. Now log data is placed at /data/user-requests.data .

**Comment by alinefm** [comment] 2016-10-21 13:34
I could not reproduce that anymore on Fedora 24.
I will close this issue by now. Please, reopen if the problem persists to you.

**Closed by alinefm** 2016-10-21 13:34 UTC
