### ISSUE TITLE
 The filter of of the user activity log shows loading forever

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#144] opened 2016-06-30 06:26 UTC
# === Problem Description ===================================
# ===========================================================

The filter of of the user activity log shows loading forever, when tried to filter with any keyword after login in with the incorrect user.
# === Steps to Reproduce ====================================
# ===========================================================
1. Login with the incorrect user. For ex 9.132.123.12 rather than root
2. Login with correct user.
3. Go to the user activity log in wok tab
4. Try to filter with any keyword.

**Comment by alinefm** [comment] 2016-07-05 14:41
Hi @mesmriti 

Everything is working fine in my tests.

I did exactly what you described: tried to login with invalid credentials, when login with valid credentials and I could filter the user log entries without problems.

Could you confirm that and provide more details on how to reproduce? Maybe some tiny different on setup or so.

**Comment by mesmriti** [comment] 2016-07-15 07:18
might be. I am still able to reproduce the issue. Sharing the screen shots.
![screenshot from 2016-07-15 12 47 14](https://cloud.githubusercontent.com/assets/13163405/16866574/553021c4-4a8a-11e6-8911-dc02986a1443.png)
![screenshot from 2016-07-15 12 47 27](https://cloud.githubusercontent.com/assets/13163405/16866585/5f95cbe6-4a8a-11e6-9108-86a8127200ca.png)

**Comment by alinefm** [comment] 2016-09-08 14:10
Hi @mesmriti 

Could you share details about you system and setup? Which OS and browser you are using?

I still could not reproduce it.

**Comment by pvital** [comment] 2016-09-08 21:39
While testing code for 2.3 release in a Ubuntu 16.04 Server system, I had the same issue.

Here is the main page, listing all activities (only have Wok running):

![screenshot from 2016-09-08 18-35-12](https://cloud.githubusercontent.com/assets/699330/18367815/46a31cf8-75f3-11e6-829e-f6be886d0c37.png)

Here is the result when I type the word 'bla' to filter only entries of 'bla' user:

![screenshot from 2016-09-08 18-35-54](https://cloud.githubusercontent.com/assets/699330/18367875/7e631d6e-75f3-11e6-8c26-551a25cccc07.png)

**Comment by alinefm** [comment] 2016-09-12 19:22
Hi @pvital 

I've just tested that on a Kimchi installed on CentOS 7 + Firefox 48.0.1 and I could filter the user log entries without issues.

I don't see it should be a problem on host enviroment. Could you check your browser version?

**Comment by pvital** [comment] 2016-09-12 19:42
The client is Fedora 24 running Google Chrome 53.0.2785.92

**Comment by alinefm** [comment] 2016-09-13 13:36
JFYI I tried on Google Chrome 53.0.2785.101 and the filter worked as expected.

**Comment by pvital** [comment] 2016-09-13 13:46
:-O

I'll re-test it later.

**Comment by alinefm** [comment] 2016-10-21 14:00
Any update on that? Otherwise, I will close this issue as it seems to be working on Chrome and Firefox without issues.

**Comment by pvital** [comment] 2016-10-25 13:50
Re-tested and it's working.

**Comment by biancafc** [comment] 2016-11-30 16:21
Reopening this issue, got the same error described with Fedora 25, tested in Safari and Firefox.

**Comment by alinefm** [comment] 2016-12-07 12:27
@biancafc Could you give details about the Firefox version?

**Comment by lcorreia** [comment] 2016-12-07 14:47
It happens with my browser too: Google Chrome Version 54.0.2840.71 (64-bit)
Server running on Ubuntu 16.10 VM.

**Comment by biancafc** [comment] 2016-12-07 17:58
@alinefm Firefox version: 50.0.2

**Comment by biancafc** [comment] 2016-12-12 16:36
@alinefm, @lcorreia I'm tryting to reproduce this error again, when I try to log in as admin, user logs filter works fine. However, when I try to reproduce this issue using a regular user, I can't test it because of issue [#187](https://github.com/kimchi-project/wok/issues/187) which is blocking me.

**Comment by biancafc** [comment] 2016-12-12 17:13
update: I can repdoduce the issue on Debian 8, so I will work on that environment.

**Closed** 2016-12-14 17:27 UTC
Labels: bug
