### ISSUE TITLE
Debian: make-deb.sh fails with "cannot touch '[..]/etc/nginx/conf.d/wok.conf': No such file or directory"

### ISSUE THREAD

**Issue by abbbi** [kimchi-project/wok#107] opened 2016-04-25 20:34 UTC
Hi,

bulding the debian package on my system fails with:

touch /tmp/tmp.W7uSyPxgPT/etc/nginx/conf.d/wok.conf
touch: cannot touch '/tmp/tmp.W7uSyPxgPT/etc/nginx/conf.d/wok.conf': No such file or directory
Makefile:1000: recipe for target 'install-data-local' failed
make[2]: **\* [install-data-local] Error 1
make[2]: Leaving directory '/home/vm/kimchi-project-wok-f3083e6'
Makefile:796: recipe for target 'install-am' failed
make[1]: **\* [install-am] Error 2
make[1]: Leaving directory '/home/vm/kimchi-project-wok-f3083e6'
Makefile:494: recipe for target 'install-recursive' failed
make: **\* [install-recursive] Error 1
dpkg-deb: error: failed to open package info file `/tmp/tmp.W7uSyPxgPT/DEBIAN/control' for reading: No such file or directory

**Comment by pvital** [comment] 2016-04-26 12:56
Hello @abbbi 

What's your system? Ubuntu or Debian?

**Comment by abbbi** [comment] 2016-04-26 12:59
Debian jessie

**Comment by pvital** [comment] 2016-04-26 21:58
@abbbi I'm going to check this.

**Comment by alinefm** [comment] 2016-10-21 13:58
I could not reproduce it with the latest unstable debian image.
Could you check again? Otherwise, I think we can close this issue.

**Comment by pvital** [comment] 2016-10-25 16:20
I also could make the deb of wok (from official git repo) in a Debian Jessie (updated). The full output of the 'make deb' command is here: http://paste.debian.net/889721/

The part where make installs the wok.conf file is:

```
mkdir -p /tmp/tmp.VIZ0gKiWMZ/etc/wok/
/usr/bin/install -c -m 644 src/dhparams.pem /tmp/tmp.VIZ0gKiWMZ/etc/wok/dhparams.pem
touch /tmp/tmp.VIZ0gKiWMZ/etc/nginx/conf.d/wok.conf
mkdir -p /tmp/tmp.VIZ0gKiWMZ/etc/logrotate.d/
touch /tmp/tmp.VIZ0gKiWMZ/etc/logrotate.d/wokd
```

**Comment by alinefm** [comment] 2016-12-07 12:23
Closing issue based on latest comments. Please, reopen if the problem persists.

**Closed by alinefm** 2016-12-07 12:23 UTC
Labels: bug
