### ISSUE TITLE
Hygiene - Unable to 'Download' a set of filtered 'User Activity Log' entries

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#149] opened 2016-07-14 09:22 UTC
#=== Steps to Reproduce ====================================
#===========================================================
1.In the 'User Activity Log' filter on a value for specific 'message', ie: activate
2.Now I want to 'Download' just those entries from the filtering.
3.The 'Download' shows all entries, not just the 'filtered' ones.
4.This should work like the 'Advanced Search' now option does.

**Comment by lcorreia** [comment] 2016-08-09 19:47
This is working by design, since the filtering is a UI feature which data backend does not have access to. The Download button will work only for the last result of Advanced Search.

**Comment by alinefm** [comment] 2016-09-08 14:09
Closing based on last comment.

**Closed by alinefm** 2016-09-08 14:09 UTC
