### ISSUE TITLE
Session time out is not configurable via wok.conf

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/wok#106] opened 2016-04-20 13:15 UTC
Session time out is not configurable via wok.conf
Do we have a reason behind this ?
I guess it would be great if we can support session time out as a configurable value in the wok.conf

Please let know your thoughts !!!

**Comment by pvital** [comment] 2016-04-20 14:00
@chandrureddy I guess there's an issue opened to see this.

@alinefm do you know if it's be handled by some issue?

**Comment by chandrureddy** [comment] 2016-04-26 11:41
@alinefm @pvital 
We have experimented on session time out and in order to have session time out beyond 10 mins, the following was done (let us say dashboard to be alive beyond 10 mins).

1. stop wokd service
   systemctl stop wokd.service

2. vi  /usr/lib/python2.7/site-packages/wok/config.py

Look out for variable : SESSIONSTIMEOUT = 10    # session time out is 10 minutes
#value mentioned is in minutes

3. vi /etc/nginx/conf.d/wok.conf.in  
   # This step may not 100% required I guess
    # Timeout set to 10 minutes to avoid the 504 Gateway Timeout
   # value is secs
   proxy_connect_timeout       600;
   proxy_send_timeout          600;
   proxy_read_timeout          600;
   send_timeout                600;
 
4. vi /etc/wok/plugins.d/gingerbase.conf
# value is in minutes
tools.sessions.timeout = 10

3. start the wokd service
   systemctl start wokd.service

But I feel we should bring in mechanism where we have one central configurable variable which would help in setting session time out (ie let us say /etc/wok.conf).

**Comment by laggarcia** [comment] 2016-04-26 17:16
I think this is a duplicate of issue #19.

**Comment by pvital** [comment] 2016-04-26 21:45
@laggarcia you are right.

@chandrureddy I suggest you to close this issue as duplicate of issue #19

**Closed** 2016-04-27 02:08 UTC
