### ISSUE TITLE
wokd service getting failed

### ISSUE THREAD

**Issue by kishanpant** [kimchi-project/wok#117] opened 2016-05-24 05:55 UTC
I installed kimchi 2.1 on CentOS7.2 and Ubuntu 16.04 using RPM and DEB packages by following the instruction given in http://kimchi-project.github.io/kimchi/downloads/ but after some time service getting failed. Please help me in this issue.

![kimchi-1](https://cloud.githubusercontent.com/assets/19544948/15493534/3a72133a-21a2-11e6-9c53-739a827df728.png)
![kimchi-2](https://cloud.githubusercontent.com/assets/19544948/15493533/3a6ecedc-21a2-11e6-802d-c207d55dd662.png)

**Comment by pvital** [comment] 2016-05-24 14:27
Hello @kishanpant 

Could you provide use the output of the command "systemctl -l status wokd.service" and the content of the file /var/log/wok/wok-errorl.log (use can use http://paste.fedoraproject.org to copy and paste the content and send us the link provided).

I installed Wok and Kimchi on CentOS 7.2 and they are OK for me. You can see more details about what I did here: https://github.com/kimchi-project/kimchi/issues/845

**Comment by OnigamiSama** [comment] 2016-05-29 13:15
I have the same issue on a fresh CentOS7.2

["systemctl -l status wokd.service"](http://paste.fedoraproject.org/372071/45275171/)
[/var/log/wok/wok-errorl.log](http://paste.fedoraproject.org/372072/52765314/)

**Comment by OnigamiSama** [comment] 2016-06-02 03:20
I had the same issue and it was because I was running it on a VM with no nested virtualization support.

**Comment by pvital** [comment] 2016-06-02 12:36
@OnigamiSama if you have installed the Kimchi plugin on wok, it's true because Kimchi needs libvirtd.service running before wokd.service starts. With no nested virtualization support enabled, libvirt will not start.

**Comment by alinefm** [comment] 2016-07-05 13:38
Hi @kishanpant 

Please, make sure you have nested virtualization properly configured with you are installing Wok in a VM.
You can get some details on https://kashyapc.com/2012/01/14/nested-virtualization-with-kvm-intel/

I will close this issue by now based on previous comments, but feel free to reopen if the problem persists and provide more details on how to reproduce it so we can easily identify the root cause and solve it.

**Closed by alinefm** 2016-07-05 13:38 UTC
