### ISSUE TITLE
Wok success message is not disappearing automatically.

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/wok#156] opened 2016-08-12 08:40 UTC
Wok success message is not disappearing automatically. message is displayed till user dismiss it.
previously success message used to disappear after a certain time duration.

![success message](https://cloud.githubusercontent.com/assets/13199397/17617212/816cc2f2-6096-11e6-9123-9596a8bf750e.jpg)

**Comment by danielhb** [comment] 2016-08-12 18:16
This is not a bug. This is an accessibility fix @samhenri  implemented. The message must remain there until the user dismisses it manually.

**Comment by chandrureddy** [comment] 2016-08-16 07:06
@danielhb @samhenri , I guess asking user to close even successful messages may be cumbersome at times. This is kind of user experience where user may feel frustrating to even close the success messages.

Another use case on z390x, where user may choose 2000 I/O devices and enable them. So asking user to close 2000 successful messages would be killer.

Some how I feel success message should not mandate user to close them !!! Please re-think !!!

**Comment by danielhb** [comment] 2016-08-16 12:43
@chandrureddy in the case where 2000 requests is made at once I think the UI can handle differently, with a single success/error message. 2000 success messages appearing at once isn't viable anyways.

Now, I agree that the success message disappearing automatically looks better than going there and closing it. Point is that AFAIK this is an accessibility guideline, not a design choice. The idea is that a screen reader must have time to read all the screen contents for the vision impaired user. Due to that the message can't disappear without user interaction.

We can discuss to see if we can reach a common ground between how to follow accessibility rules and not be annoying at the same time. This is why I am mentioning @samhenri in this bug - he is more experienced in this than I am.

**Comment by chandrureddy** [comment] 2016-08-16 12:53
@danielhb, for sure there is scope for improvisation on the number of records handling on s390x device handling. By having this restriction it should not be killer immediate :-)

**Comment by samhenri** [comment] 2016-08-16 15:45
@chandrureddy @danielhb Like I replied on the mailing list, I think we can check if the new message has the same text as the older message and remove the old message and add a new alert inside the container. We could add time stamps since the message text is the same but the event happened before. As for the accessibility issues, the idea is that once an alert appears on the screen, the keyboard focus should jump to the alert.

**Comment by alinefm** [comment] 2016-10-21 14:05
AFAIK the closable option in the message widget is configurable. So if you want to dismiss it automatically set "closable' to false in your plugin code.

Closing this issue as there is nothing to do on Wok side.

**Closed by alinefm** 2016-10-21 14:05 UTC
